# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d99f0931bc51f75d3980387c5fc85e80b400ba3945403aaddff63f8338073739cffef4441e14b838e04440363cc7bd1e4b181d5ece3b8151b07f24889ba91d6

test:
  secret_key_base: fcc6025fbfcf6fc55f71cab6b358dfb18dd31631e05302ea98901043d59e656a00f65c26ebdc8cfeafbbced3e9c56e65a345aa3f5da7d93005b484931426f945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>